name: Docker Build and Push
description: Build the Java microservice
inputs:
  run_number:
    required: true
    description: The GitHub Actions Workflow run number
  github_repo:
    description: 'The github repo'
    required: true
  github_token:
    description: 'The github token'
    required: true
  github_actor:
    description: 'The github actor'
    required: true
  dockerhub_username:
    description: 'The dockerhub username'
    required: true
  dockerhub_password:
    description: 'The dockerhub password'
    required: true
  service_directory:
    description: 'The directory holding the microservice'
    required: true
  lambda_build:
    description: 'Whether to build the lambda executable or not'
    required: true
    default: true
  postman_build:
    description: 'Whether to build the postman test'
    required: true
    default: true
  liquibase_build:
    description: 'Whether to build the liquibase packages'
    required: true
    default: true
  docker_build:
    description: 'Whether to build the docker images'
    required: true
    default: true
  systemd_build:
    description: 'Whether to build the systemd packages'
    required: true
    default: true
  run_tests:
    description: 'Whether to run tests'
    required: true
    default: true
  codefresh_token:
    description: 'The codefresh token'
    required: true
  github_codefresh_token:
    description: 'The github codefresh token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Clone code repo
      uses: actions/checkout@v2

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v7

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: 5.x

    - name: Set Version
      run: echo "PACKAGE_VERSION=$(date +'%Y%m%d').${{ github.run_number }}.${{ github.run_attempt }}" >> $GITHUB_ENV
      shell: bash

    - name: Set up JDK 1.17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: adopt
        cache: 'maven'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      if: ${{ inputs.docker_build == 'true' }}
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_password }}

    - uses: DeLaGuardo/setup-graalvm@4.0
      with:
        graalvm: '22.3.2'
        java: 'java17'
        arch: 'amd64'

    - name: Install native-image component
      run: gu install native-image
      shell: bash

    - name: Checkstyle
      run: ./mvnw --batch-mode checkstyle:check
      shell: bash
      working-directory: java

    - name: Install modules
      run: ./mvnw --batch-mode install -DskipTests
      shell: bash
      working-directory: java

    - name: Test Backend
      if: ${{ inputs.run_tests == 'true' }}
      run: ./mvnw --batch-mode test
      shell: bash
      working-directory: java/${{ inputs.service_directory }}

    - name: Test Shared Library
      if: ${{ inputs.run_tests == 'true' }}
      run: ./mvnw --batch-mode test
      shell: bash
      working-directory: java/microservice-utils

    - name: Generate JaCoCo Badges
      if: ${{ inputs.run_tests == 'true' }}
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: java/${{ inputs.service_directory }}/target/jacoco-report/jacoco.csv
        coverage-badge-filename: ${{ inputs.service_directory }}.svg
        branches-badge-filename: ${{ inputs.service_directory }}-branches.svg

    - name: Generate JaCoCo Badges for Shared Library
      if: ${{ inputs.run_tests == 'true' }}
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: java/microservice-utils/target/site/jacoco/jacoco.csv
        coverage-badge-filename: microservice-utils.svg
        branches-badge-filename: microservice-utils-branches.svg

    - name: Update resources
      if: ${{ inputs.run_tests == 'true' && steps.branch-name.outputs.current_branch == 'main' }}
      uses: test-room-7/action-update-file@v1.6.0
      with:
        file-path: |
          .github/badges/microservice-utils.svg
          .github/badges/microservice-utils-branches.svg
        commit-msg: Update badges
        github-token: ${{ inputs.github_token }}

    # The non-MySQL Docker image is built and pushed.
    - name: Build, tag, and push image to Dockerhub
      if: ${{ inputs.docker_build == 'true' }}
      run: |
        docker buildx build -f src/main/docker/Dockerfile.legacy-jar -t harrisonmeister/cf-octopub-${{ inputs.service_directory }}:${{ env.PACKAGE_VERSION }} -t harrisonmeister/cf-octopub-${{ inputs.service_directory }}:latest --platform=linux/amd64 --push .
      shell: bash
      working-directory: java/${{ inputs.service_directory }}

    - name: report image by action
      with:
        # Name of runtime to implement the enrichment
        CF_RUNTIME_NAME: 'codefresh-local'

        # Documentation - https://docs.github.com/en/actions/security-guides/encrypted-secrets
        CF_API_KEY: ${{ inputs.codefresh_token }}

        # Name of Container registry integration
        CF_CONTAINER_REGISTRY_INTEGRATION: 'harrisonmeister-dockerhub'

        # The git branch which is related for the commit
        CF_GIT_BRANCH: ${{ github.ref_name }}

        # Image path to enrich 
        CF_IMAGE: docker.io/${{ inputs.dockerhub_username }}/cf-octopub-${{ inputs.service_directory }}-mysql:${{ env.PACKAGE_VERSION }}

        # GitHub Access token !! Committing a plain text token is a security risk. We highly recommend using encrypted secrets. !!
        # Documentation - https://docs.github.com/en/actions/security-guides/encrypted-secrets
        CF_GITHUB_TOKEN: ${{ inputs.github_codefresh_token }}    

        # # Name of Jira integration
        CF_ISSUE_TRACKING_INTEGRATION: 'harrisonmeister-jira' 

        # # String starting with the issue ID to associate with image
        CF_JIRA_MESSAGE: 'OC-1'

        # # Jira project filter
        CF_JIRA_PROJECT_PREFIX: "OC"
      uses: codefresh-io/codefresh-report-image@latest