apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopub-product-production
  annotations:
    codefresh.io/product: octopub-product
spec:
  project: default
  source:
    repoURL: https://github.com/harrisonmeister/cf-octopub.git
    targetRevision: HEAD
    path: codefresh/helm/octopub-products/production
  destination:
    server: https://kubernetes.default.svc
    namespace: cf-production
  syncPolicy:
    automated:  
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true