name: Build Audits
permissions:
  contents: write
  packages: write
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - '**/*'
      - '!.github/badges/*'
      - '!README.md'
      - '!python/**/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Audit Microservice
        uses: ./github/java-microservice
        with:
          run_number: ${{ github.run_number }}
          github_repo: ${{ github.repository }}
          github_token: ${{ github.token }}
          github_actor: ${{ github.actor }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
          octopus_url: ${{ secrets.DSC_OCTOPUS_URL }}
          octopus_apikey: ${{ secrets.DSC_OCTOPUS_API }}
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          service_directory: audit-microservice

      - name: Build Audits Helm Chart
        uses: ./github/helm
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          chart_directory: octopub-audits-mysql
          octopus_url: ${{ secrets.DSC_OCTOPUS_URL }}
          octopus_apikey: ${{ secrets.DSC_OCTOPUS_API }}